2025-05-23 20:31:24,249 - INFO - [logging.py:51] - ==================================================
2025-05-23 20:31:24,249 - INFO - [logging.py:52] - Application starting at 2025-05-23 20:31:24
2025-05-23 20:31:24,249 - INFO - [logging.py:53] - Logging initialized at level INFO
2025-05-23 20:31:24,249 - INFO - [logging.py:54] - Log file: logs\nc_client_20250523_203124.log
2025-05-23 20:31:24,249 - INFO - [logging.py:55] - ==================================================
2025-05-23 20:31:24,249 - INFO - [main.py:27] - NetControl Client starting...
2025-05-23 20:31:36,899 - INFO - [encryption.py:27] - AES encryption initialized successfully
2025-05-23 20:31:36,899 - INFO - [client.py:93] - Connected to central server at 192.168.1.120:5001 with AES encryption
2025-05-23 20:31:36,928 - INFO - [client.py:150] - Successfully logged in as admin
2025-05-23 20:31:37,229 - INFO - [system_monitor.py:31] - Starting resource monitoring
2025-05-23 20:31:37,229 - INFO - [system_monitor.py:27] - Hardware monitoring thread started
2025-05-23 20:31:37,229 - INFO - [manager.py:559] - Starting connection health monitoring
2025-05-23 20:31:37,229 - INFO - [manager.py:555] - Connection health monitoring thread started
2025-05-23 20:31:41,880 - INFO - [manager.py:81] - Connection established with 192.168.1.120:5000 using AES encryption
2025-05-23 20:31:41,915 - INFO - [encryption.py:27] - AES encryption initialized successfully
2025-05-23 20:31:42,596 - INFO - [client.py:331] - Registered server 192.168.1.120:5000
2025-05-23 20:31:42,604 - ERROR - [client.py:464] - Setting sharing status failed: no such table: active_connections
2025-05-23 20:31:42,605 - WARNING - [client.py:339] - Failed to share server 192.168.1.120:5000: no such table: active_connections
2025-05-23 20:31:42,617 - INFO - [manager.py:179] - Successfully registered server 192.168.1.120:5000 with central server
2025-05-23 20:31:42,623 - ERROR - [client.py:464] - Setting sharing status failed: no such table: active_connections
2025-05-23 20:31:42,623 - WARNING - [manager.py:193] - Failed to enable sharing for 192.168.1.120:5000: no such table: active_connections
2025-05-23 20:32:02,523 - ERROR - [client.py:200] - Error receiving data: [WinError 10038] An operation was attempted on something that is not a socket
2025-05-23 20:32:02,523 - ERROR - [client.py:326] - Error in RDP display loop: [WinError 10038] An operation was attempted on something that is not a socket
2025-05-23 20:32:34,819 - INFO - [client.py:619] - Disconnected from central server
2025-05-23 20:32:34,819 - INFO - [central_server_tab.py:585] - Restarting application after logout...
2025-05-23 20:32:34,819 - INFO - [manager.py:652] - All connections closed
2025-05-23 20:32:35,003 - INFO - [system_monitor.py:44] - Resource monitoring stopped
